routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::resource('license_keys', 'LicenseKeyController');

Route::redirect('/', '/dashboard')->name('dashboard');

Route::get('/players', 'PlayerController@index');

Route::get('2FAForm', 'TwoFactorController@verifyForm')->name('2FAForm');

Route::post('2FAVerify', 'TwoFactorController@verify')->name('2FAVerify');

Route::get('/send-reference-mail', 'ReferenceController@sendReferenceEmail')->name('send-reference-mail');

Route::get('/dashboard', 'MainController@index')->name('dashboard');

Route::get('/scores', 'ScoreController@index');

Route::get('/shares', 'ShareController@index');

Route::get('/references', 'ReferenceController@index');

Route::get('/scores', 'ScoreController@index');

Route::get('/vouchers', 'VoucherDistributionController@index');

Route::get('/voucherOverview', 'VoucherDistributionController@voucherOverview');

Route::get('/getPageviews', 'GaController@getUserJourney');

Route::get('/redeemVoucher/outlet/{outlet}', 'VoucherController@redemption');

Route::get('/viewDeletedVouchers', 'VoucherController@getDeletedVouchers');

Route::get('/duplicateRedemption', 'VoucherController@duplicateRedemption');

// Defined for action of form id: restore-voucher-form
Route::post('restoreVoucher', 'VoucherController@restoreVoucher');

// Defined for action of form id: voucher-code-form
Route::post('voucherDetails', 'VoucherController@voucherDetails');

Route::resource('manageVouchers', 'VoucherController');

/*
 * Routes for overview APIs
*/
Route::get('/getDailyOverview', 'OverviewController@getDailyOverview');

Route::get('/getWeeklyOverview', 'OverviewController@getWeeklyOverview');

Route::get('/getBranchDailyOverview', 'OverviewController@getBranchDailyOverview');

Route::get('/getVoucherDailyOverview', 'VoucherDistributionController@getDailyOverview');

Route::get('/getRegistrationHourCount', 'OverviewController@getRegistrationHourCount');

/*
 * Routes for downloading CSV files
*/
Route::get('/downloadPlayersCSV', 'PlayerController@downloadCSV');
Route::get('/downloadUnredeemedVoucherCSV', 'VoucherDistributionController@downloadUnredeemedCSV');
Route::get('/downloadRedeemedVoucherCSV', 'VoucherDistributionController@downloadRedeemedCSV');
Route::get('/downloadReferencesCSV', 'ReferenceController@downloadCSV');
Route::get('/downloadScoresCSV', 'ScoreController@downloadCSV');
Route::get('/downloadSharesCSV', 'ShareController@downloadCSV');
Route::get('/downloadVouchersCSV', 'VoucherDistributionController@downloadCSV');

resources/views/common/footer.blade.php
<div class="row mb-5"></div>
<footer class="app-footer navbar fixed-bottom">
    <div class="mx-auto">
        <a href="https://uid.asia" target="_blank">
            Unicom Interactive Digital
        </a>
        <span>
            © 2019 Unicom Interactive Digital (UID).
        </span>
    </div>
</footer>

resources/views/common/header.blade.php
<header class="app-header navbar navbar-expand-lg">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" data-toggle="sidebar-show" type="button">
        <span class="navbar-toggler-icon">
        </span>
    </button>
    <a class="navbar-brand" href="/dashboard">
        <img alt="CoreUI Logo" class="navbar-brand-full ml-3" src="{{ asset('img/brand/logo.png') }}" width="100%" />
        <img alt="CoreUI Logo" class="navbar-brand-minimized ml-3" src="{{ asset('img/brand/logo-small.png') }}" width="100%" />
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" data-toggle="sidebar-lg-show" type="button">
        <span class="navbar-toggler-icon">
        </span>
    </button>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
        </span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        @if (Auth::check())
        <ul class="navbar-nav mr-auto ml-5">
            <li class="nav-item">
                <a class="nav-link disabled label-event" href="#">Event :</a>
            </li>
            <li class="nav-item dropdown">
                <div id="eventDropdown"></div>
            </li>
            <li class="nav-item dropdown ml-3">
                <div id="sourceIdentifierDropdown"></div>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-auto ul-user">
            <div class="nav-item dropdown">
                <a id="dropdownMenuLink" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {{ Auth::user()->name }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item d-none" href="#">
                        <i class="icon-wrench text-dark">
                        </i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="icon-power text-dark">
                        </i>
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>
        </ul>
        @endif
    </div>

</header>

resources/views/common/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="/dashboard">
                    <i class="nav-icon icon-speedometer"></i> Dashboard
                </a>
            </li>
            <li class="nav-title">DATA</li>
            <li class="nav-item nav-dropdown d-none">
                <a class="nav-link nav-dropdown-toggle">
                    <i class="nav-icon icon-user"></i> Players
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="/players">
                            <i class="nav-icon icon-people"></i> Database
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/scores">
                            <i class="nav-icon icon-game-controller"></i> Scores
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/shares">
                            <i class="nav-icon icon-share"></i> Shares
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle">
                    <i class="nav-icon icon-present"></i> Vouchers
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="/vouchers">
                            <i class="nav-icon icon-layers"></i> Database
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/voucherOverview">
                            <i class="nav-icon icon-chart"></i> Overview
                        </a>
                    </li>
                    <li class="nav-item d-none">
                        <a class="nav-link" href="{{ route('manageVouchers.index') }}">
                            <i class="nav-icon icon-wrench"></i> Manage
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>