routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::resource('license_keys', 'LicenseKeyController');

Route::redirect('/', '/dashboard')->name('dashboard');

Route::get('/players', 'PlayerController@index');

Route::get('2FAForm', 'TwoFactorController@verifyForm')->name('2FAForm');

Route::post('2FAVerify', 'TwoFactorController@verify')->name('2FAVerify');

Route::get('/send-reference-mail', 'ReferenceController@sendReferenceEmail')->name('send-reference-mail');

Route::get('/dashboard', 'MainController@index')->name('dashboard');

Route::get('/scores', 'ScoreController@index');

Route::get('/shares', 'ShareController@index');

Route::get('/references', 'ReferenceController@index');

Route::get('/scores', 'ScoreController@index');

Route::get('/vouchers', 'VoucherDistributionController@index');

Route::get('/voucherOverview', 'VoucherDistributionController@voucherOverview');

Route::get('/getPageviews', 'GaController@getUserJourney');

Route::get('/redeemVoucher/outlet/{outlet}', 'VoucherController@redemption');

Route::get('/viewDeletedVouchers', 'VoucherController@getDeletedVouchers');

Route::get('/duplicateRedemption', 'VoucherController@duplicateRedemption');

// Defined for action of form id: restore-voucher-form
Route::post('restoreVoucher', 'VoucherController@restoreVoucher');

// Defined for action of form id: voucher-code-form
Route::post('voucherDetails', 'VoucherController@voucherDetails');

Route::resource('manageVouchers', 'VoucherController');

/*
 * Routes for overview APIs
*/
Route::get('/getDailyOverview', 'OverviewController@getDailyOverview');

Route::get('/getWeeklyOverview', 'OverviewController@getWeeklyOverview');

Route::get('/getBranchDailyOverview', 'OverviewController@getBranchDailyOverview');

Route::get('/getVoucherDailyOverview', 'VoucherDistributionController@getDailyOverview');

Route::get('/getRegistrationHourCount', 'OverviewController@getRegistrationHourCount');

/*
 * Routes for downloading CSV files
*/
Route::get('/downloadPlayersCSV', 'PlayerController@downloadCSV');
Route::get('/downloadUnredeemedVoucherCSV', 'VoucherDistributionController@downloadUnredeemedCSV');
Route::get('/downloadRedeemedVoucherCSV', 'VoucherDistributionController@downloadRedeemedCSV');
Route::get('/downloadReferencesCSV', 'ReferenceController@downloadCSV');
Route::get('/downloadScoresCSV', 'ScoreController@downloadCSV');
Route::get('/downloadSharesCSV', 'ShareController@downloadCSV');
Route::get('/downloadVouchersCSV', 'VoucherDistributionController@downloadCSV');

app/Voucher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Voucher extends Model
{
    use SoftDeletes;

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function voucher_distributions()
    {
        return $this->hasMany('App\VoucherDistribution');
    }

    public function voucher_stocks()
    {
        return $this->hasOne('App\VoucherStock');
    }

    public function event()
    {
        return $this->belongsTo('App\Event');
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'event_id', 'code', 'description', 'image',
    ];
}

app/Http/Controllers/VoucherController.php
<?php

namespace App\Http\Controllers;

use App\RedeemLocation;
use Auth;
use App\Voucher;
use App\VoucherDistribution;
use App\Event;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

class VoucherController extends Controller
{
    /**
     * Get the saved event ID from the cookie
     */
    public function getEventId()
    {
        $eventId = 1;
        if (isset($_COOKIE["eventID"])) {
            if ($_COOKIE["eventID"] != "") {
                $eventId = $_COOKIE["eventID"];
            }
        }

        return $eventId;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventId = self::getEventId();

        $vouchers = Voucher::where('event_id', $eventId)->get();
        $events = Event::all();

        return view('dashboard.voucher.manageVouchers', compact('vouchers'), compact('events'))
            ->with('i', 0)
            ->with('selectedEventId', $eventId);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'code' => 'required',
            'description' => 'required',
        ]);

        $fileName = null;
        $extension = null;
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $extension = strtolower($request->image->extension());

            // If the file extension is not jpeg, jpg or png
            if ($extension != "jpeg" && $extension != "jpg" && $extension != "png") {
                return redirect()->route('manageVouchers.index')
                    ->withErrors(array('image' => 'Please upload valid image file'));
            }

            // Store the image file in
            $request->image->storeAs('images/voucher_images', $fileName, ['disk' => 'public']);
        }

        $voucher = array(
            'user_id' => Auth::user()->id,
            'event_id' => $request->event_id,
            'code' => $request->code,
            'description' => $request->description,
            'image' => $fileName,
        );

        Voucher::create($voucher);

        return redirect()->route('manageVouchers.index');
    }

    /**
     * Redeem the voucher.
     *
     * @param  \App\Voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function redemption(Request $request)
    {
        $outlet = $request->outlet;

        $check_outlet = RedeemLocation::where('outlet_code', $outlet)->first();

        if (!is_null($check_outlet)) {
            $request->session()->put('redeem_outlet', $check_outlet->outlet_code);
            return view('dashboard.voucher.redeemVouchers')->with('outlet', $outlet);
        } else {
            # Redeem outlet not found
            return redirect()->route('dashboard');
        }
    }

    /**
     * Show the details of the voucher based on the entered voucher code.
     *
     * @return \Illuminate\Http\Response
     */
    public function voucherDetails(Request $request)
    {
        $outlet_code = $request->redeem_location;
        $voucher_code = $request->voucher_code;

        $voucher_distribution = VoucherDistribution::where('voucher_code', $voucher_code)->first();
        $redeem_location = RedeemLocation::where('outlet_code', $outlet_code)->first();

        $voucher = null;

        # Check if this voucher code exists
        if ($voucher_distribution != null) {
            # Check if this voucher has been redeemed
            if ($voucher_distribution->redeem_location == null && $voucher_distribution->redeem_time == null) {
                $voucher = Voucher::where('id', $voucher_distribution->voucher_id)->first();

                if (!$redeem_location == null) {
                    $voucher_distribution->redeem_location_id = $redeem_location->id;
                    $voucher_distribution->redeem_time = \Carbon\Carbon::now();
                    $voucher_distribution->save();
                }

                return view('dashboard.voucher.voucherDetails')
                    ->with('redeem_location', $redeem_location)
                    ->with('voucher_code', $voucher_code)
                    ->with('voucher', $voucher);
            } else {
                return view('dashboard.voucher.duplicateRedemption')
                ->with('redeem_time', $voucher_distribution->redeem_time)
                ->with('outlet_code', $outlet_code);
            }
        } else {
            return view('dashboard.voucher.invalidVouchers')
            ->with('outlet_code', $outlet_code);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function redeemedVoucherCode()
    {
        return view('dashboard.voucher.redeemedVoucherCode');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function show(Voucher $voucher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $voucher = Voucher::find($id);

        return view('dashboard.voucher.editVoucher', compact('voucher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'code' => 'required',
            'description' => 'required',
        ]);

        $fileName = null;
        $extension = null;

        // If there is file sent
        // else check if is there a file previously
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $extension = strtolower($request->image->extension());

            // If the file extension is not jpeg, jpg or png
            if ($extension != "jpeg" && $extension != "jpg" && $extension != "png") {
                return redirect()->route('manageVouchers.edit')
                    ->withErrors(array('image' => 'Please upload valid image file'));
            }

            // Store the image file in
            $request->image->storeAs('images/voucher_images', $fileName, ['disk' => 'public']);
        } else {
            if ($request->fileName != "") {
                $fileName = $request->fileName;
            }
        }

        $updatedVoucher = array(
            'user_id' => Auth::user()->id,
            'code' => $request->code,
            'description' => $request->description,
            'image' => $fileName,
        );

        $voucher = Voucher::find($id);
        $voucher->update($updatedVoucher);

        return redirect()->route('manageVouchers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $voucher = Voucher::find($id);

        echo $voucher;

        $voucher->delete();

        return redirect()->route('manageVouchers.index');
    }

    /**
     * Display a listing of the deleted vouchers.
     *
     * @return \Illuminate\Http\Response
     */
    public function getDeletedVouchers()
    {
        $eventId = self::getEventId();

        $vouchers = Voucher::onlyTrashed()
                    ->where('event_id', $eventId)
                    ->get();

        return view('dashboard.voucher.deletedVouchers')
            ->with('vouchers', $vouchers)
            ->with('i', 0);
    }

    /**
     * Restore a deleted voucher.
     *
     * @return \Illuminate\Http\Response
     */
    public function restoreVoucher(Request $request)
    {
        $voucherId = $request->voucherId;

        Voucher::onlyTrashed()
            ->where('id', $voucherId)
            ->restore();

        return redirect()->route('manageVouchers.index');
    }

    public function invalidVoucherCode(Request $request)
    {
        $voucher_code = $request->voucher_code;
        $invalid_voucher = VoucherDistribution::where('voucher_code', $voucher_code)->first();
    }
}

resources/views/dashboard/voucher/duplicateRedemption.blade.php
@extends('layouts.voucherRedemption')
@section('content')

<main>
    <div class="container col-sm-6">
        <div class="animated fadeIn text-center">
            <div class="card mt-5">
                    <div class="card-body">
                    <h1 class="text-header" style="padding-bottom:5%;">Duplicate Redemption Vouchers!</h1>
                    <p class="alert alert-danger">Sorry, this voucher has been redeemed at<br>{{ $redeem_time }} </p>
                    <a class="btn btn-dark" href="/redeemVoucher/outlet/<?=$outlet_code; ?>">Go Back</a>
                </div>
            </div>
        </div>
    </div>
</main>

@endsection

resources/views/dashboard/voucher/editVoucher.blade.php
@extends('layouts.app')
@section('content')

<div class="app-body">
    @include('common.sidebar')

    <main class="main">
        <div class="container-fluid mt-4">
            <div class="animated fadeIn text-center">
                <div class="row justify-content-center">
                    <div class="col-sm-12 col-lg-8">
                        <div class="card">
                            <div class="card-header">
                                Edit Voucher
                            </div>
                            <div class="card-body">
                                <form action="{{ route('manageVouchers.update', $voucher->id) }}" method="POST"
                                    enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')

                                    <div class="form-group">
                                        <label for="code-input">Code</label>
                                        <input type="text" class="form-control text-center" id="code-input" name="code"
                                            value="{{ $voucher->code }}">
                                        @error('code')
                                        <div class="alert alert-danger mt-1">{{ $message }}</div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="desc-input">Description</label>
                                        <textarea class="form-control text-center" id="desc-input" rows="2"
                                            name="description" value="fsa">{{ $voucher->description }}</textarea>
                                        @error('description')
                                        <div class="alert alert-danger mt-1">{{ $message }}</div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <p>Image</p>
                                        <img src="{{ asset('/images/voucher_images/' . $voucher->image) }}"
                                            alt="Voucher Image" style="width: 80%">
                                    </div>
                                    <div class="form-group">
                                        <label><small>Update image:</small></label>
                                        <div class="custom-file">
                                            <input type="hidden" name="fileName" value="{{ $voucher->image }}">
                                            <input type="file" class="custom-file-input" id="image-input" name="image">
                                            <label class="custom-file-label" for="image-input">Choose file</label>
                                            @error('image')
                                            <div class="alert alert-danger mt-1">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="text-center mt-4">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

@section('fileInputScript')
<script>
    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>
@endsection

@endsection

resources/views/dashboard/voucher/invalidVouchers.blade.php
@extends('layouts.voucherRedemption')
@section('content')

<main>
    <div class="container col-sm-6">
        <div class="animated fadeIn text-center">
        <div class="card mt-5">
            <div class="card-body">
                <h1 class="text-header" style="padding-bottom:5%;">Invalid Vouchers!</h1>
                <p class="alert alert-danger">Sorry, this voucher is not exist </p>
                <a class="btn btn-dark" href="/redeemVoucher/outlet/<?=$outlet_code; ?>">Go Back</a>
            </div>
        </div>
        </div>
    </div>
</main>

@endsection

resources/views/dashboard/voucher/manageVouchers.blade.php
@extends('layouts.app')
@section('content')

<div class="app-body">
    @include('common.sidebar')

    <main class="main">
        <div class="container-fluid mt-4">
            <div class="animated fadeIn text-center">
                <div class="row justify-content-center">
                    <div class="col-sm-12 col-lg-6">
                        <div class="card">
                            <div id="accordion" class="card-header" data-toggle="collapse"
                                data-target="#create-voucher-div" aria-expanded="true"
                                aria-controls="create-voucher-div">
                                Add Voucher
                                <span><i class="icon-arrow-down drop-down-arrow"></i></span>
                            </div>
                            <div id="create-voucher-div" class="collapse" data-parent="#accordion">
                                <div class="card-body">
                                    <form method="POST" action="{{ route('manageVouchers.store') }}"
                                        enctype="multipart/form-data">
                                        @csrf

                                        <div class="form-group">
                                            <label for="event-select">Event</label>
                                            <select class="form-control" id="event-select" name="event_id">
                                                @foreach ($events as $event)
                                                    @if ($event->id == $selectedEventId)
                                                    <option selected value="{{ $event->id }}">{{ $event->event_code }}</option>
                                                    @else
                                                    <option value="{{ $event->id }}">{{ $event->event_code }}</option>
                                                    @endif
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="code-input">Code</label>
                                            <input type="text" class="form-control text-center" id="code-input"
                                                name="code">
                                            @error('code')
                                            <div class="alert alert-danger mt-1">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="desc-input">Description</label>
                                            <textarea class="form-control text-center" id="desc-input" rows="2"
                                                name="description"></textarea>
                                            @error('description')
                                            <div class="alert alert-danger mt-1">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label>Image</label>
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" id="image-input"
                                                    name="image">
                                                <label class="custom-file-label" for="image-input">Choose file</label>
                                                @error('image')
                                                <div class="alert alert-danger mt-1">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="text-center mt-4">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                List of Vouchers
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Code</th>
                                                <th>Description</th>
                                                <th>Image</th>
                                                <th>Edit</th>
                                                <th>Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($vouchers as $voucher)
                                            @php
                                            $img = asset("/images/voucher_images/" . $voucher->image);
                                            @endphp
                                            <tr>
                                                <td>{{ ++$i }}</td>
                                                <td>{{ $voucher->code }}</td>
                                                <td>{{ $voucher->description }}</td>
                                                <td><img src="{{ $img }}" alt="Voucher Image" style="width: 50%"></td>
                                                <td>
                                                    <button type="button" class="btn btn-primary"
                                                        onclick="location.href='{{ route('manageVouchers.edit', $voucher->id) }}'">
                                                        <i class="icon-note"></i>
                                                    </button>
                                                </td>
                                                <td>
                                                    @php
                                                    $formId = "form" . $voucher->id;
                                                    @endphp
                                                    <form id="{{ $formId }}"
                                                        action="{{ route('manageVouchers.destroy', $voucher->id) }}"
                                                        method="POST" class='test'>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="button" class="btn btn-danger"
                                                            data-voucher="{{ $voucher->code }}"
                                                            data-voucherId="{{ $voucher->id }}"
                                                            onclick="deleteVoucher(this)">
                                                            <i class="icon-trash"></i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-5">
                    <a href="/viewDeletedVouchers" class="btn btn-primary text-white m-auto">Restore Deleted
                        Vouchers</a>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="deleteVoucherModal" tabindex="-1" role="dialog" aria-labelledby="deleteVoucherModal"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete Voucher</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete voucher with code "<b id="voucherCode"></b>"?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button id="deleteBtn" type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

@section('fileInputScript')
<script>
    function deleteVoucher(btn) {
        var voucherId = btn.getAttribute("data-voucherId");
        var voucherCode = btn.getAttribute("data-voucher");

        document.getElementById("voucherCode").innerHTML = voucherCode;
        document.getElementById("deleteBtn").setAttribute("data-voucherId", voucherId);

        $('#deleteVoucherModal').modal('show');
    }

    $('#deleteBtn').on('click', function() {
        var voucherId = $(this).attr('data-voucherId');
        var formId = "form" + voucherId;

        document.getElementById(formId).submit();
    });

    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });

    $('.collapse').on('show.bs.collapse', function() {
        $(this).siblings('.card-header').addClass('active');
    });

    $('.collapse').on('hide.bs.collapse', function() {
        $(this).siblings('.card-header').removeClass('active');
    });
</script>
@endsection

@endsection

resources/views/dashboard/voucher/overview.blade.php
@extends('layouts.app')
@section('content')

<div class="app-body">
    @include('common.sidebar')

    <main class="main">
        <div class="container-fluid mt-4">
            <div class="animated fadeIn text-center">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-6">
                        <div class="card">
                            <div class="card-header">
                                Daily Overview
                            </div>
                            <div class="card-body">
                                <canvas class="chart" id="daily-overview-chart" height="100"></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-6 d-none">
                        <div class="card">
                            <div class="card-header">
                                Redemption Status
                            </div>
                            <div class="card-body">
                                <canvas class="chart" id="pie-chart" height="100"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Daily Overview by Voucher Code</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Date</th>

                                    @foreach ($dailyOverviewDateList as $item)
                                    <th>{{ $item }}</th>
                                    @endforeach
                                </tr>

                                <tr>
                                 <th>GPMA</th>
 
                                    @foreach ($dailyOverviewPerDay as $size) 
                                    <td>{{ $size->count }}</td>
                                    @endforeach
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>
</main>
</div>

@endsection